version: '2'
services:

    nuxeoperf-app:
        image: nuxeoperf
        depends_on:
          - nuxeoperf-nuxeo
          - nuxeoperf-postgresql
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nuxeoperf-postgresql:5432/nuxeoPerf
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8300:8080

    nuxeoperf-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/nuxeoPerf/postgresql/:/var/lib/postgresql/data/
        volumes:
            #- ./src/main/docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
            - ./.postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=nuxeoPerf
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=POSTGRESQL
        ports:
            - 8301:5432

    nuxeoperf-nuxeo:
        image: nuxeo:10.10
        ports:
            - "8302:8080"
        environment:
            NUXEO_CLID: ${CLID}
            NUXEO_CUSTOM_PARAM: JAVA_OPTS=$$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n\nnuxeo.url=http://nuxeoperf-nuxeo:8302/nuxeo/\norg.nuxeo.dev=true
            NUXEO_PACKAGES: nuxeo-web-ui
        volumes:
            - ".gen/nuxeo_log:/var/log/"
            - ".gen/nuxeo_store:/opt/nuxeo/server/packages/store"
            - ".gen/nuxeo_data:/var/lib/nuxeo/data:cached"
            - ".nuxeo_docker-entrypoint-initnuxeo.d:/docker-entrypoint-initnuxeo.d"
            - ".nuxeo_packages:/opt/nuxeo/packages"
            - ".nuxeo_plugins:/opt/nuxeo/server/nxserver/plugins"
            - ".nuxeo_templates:/opt/nuxeo/custom_templates"
