version: '2'
services:
    nuxeoperf-app:
        image: nuxeoperf
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nuxeoperf-postgresql:5432/nuxeoPerf
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nuxeoperf-postgresql:
        extends:
            file: postgresql.yml
            service: nuxeoperf-postgresql
