version: '2'
services:
    nuxeoperf-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/nuxeoPerf/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=nuxeoPerf
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
